rollout_type: ofa

## ---- Component search_space ----
# ---- Type ofa ----
search_space_type: ofa
search_space_cfg:
  num_cell_groups: [1, 4, 4, 4, 4, 4]
  expansions: [1, 6, 6, 6, 6, 6]
  image_size_choice: [32]
  schedule_cfg:
    kernel_choice:
        type: value
        boundary: [1, 51, 120]
        value: [[3], [3], [3]]
    width_choice:
      type: value
      boundary: [1, 180, 240]
      value: [[6], [6, 5, 4], [6, 5, 4, 3, 2]]
    depth_choice:
      type: value
      boundary: [1, 300, 360]
      value: [[4], [4, 3], [4,3,2]]
# ---- End Type ofa ----
## ---- End Component search_space ----

## ---- Component dataset ----
# ---- Type cifar10 ----
dataset_type: cifar100
dataset_cfg:
  # Schedulable attributes:
  cutout: null
# ---- End Type cifar10 ----
## ---- End Component dataset ----

objective_type: ofa_classification
objective_cfg:
  is_finetune: True
  # Schedulable attributes:
  schedule_cfg:
    soft_loss_coeff:
      type: value
      boundary: [1, 60]
      value: [0.0, 1.0]
  soft_loss_coeff: 0.0
  # latency_coeff: 1.0

final_model_type: ofa_final_model
final_model_cfg:
  backbone_type: mbv3_backbone
  genotypes: "image_size=32, cell_0=1, cell_1=4, cell_2=4, cell_3=4, cell_4=4, cell_5=4, cell_0_block_0=(1, 3), cell_1_block_0=(6, 7), cell_1_block_1=(6, 7), cell_1_block_2=(6, 7), cell_1_block_3=(6, 7), cell_2_block_0=(6, 7), cell_2_block_1=(6, 7), cell_2_block_2=(6, 7), cell_2_block_3=(6, 7), cell_3_block_0=(6, 7), cell_3_block_1=(6, 7), cell_3_block_2=(6, 7), cell_3_block_3=(6, 7), cell_4_block_0=(6, 7), cell_4_block_1=(6, 7), cell_4_block_2=(6, 7), cell_4_block_3=(6, 7), cell_5_block_0=(6, 7), cell_5_block_1=(6, 7), cell_5_block_2=(6, 7), cell_5_block_3=(6, 7)"
  backbone_cfg:
    mult_ratio: 1.0
    layer_channels: [16, 16, 24, 40, 80, 112, 160, 960, 1280]
    strides: [1, 2, 1, 2, 1, 1]
    kernel_sizes: [3, 5, 7]
    num_classes: 100
    block_type: mbv3_block
    stem_stride: 1
  # supernet_state_dict: "results/search_cifar10/final/evaluator.pt"

final_trainer_type: cnn_trainer
final_trainer_cfg:
  batch_size: 256
  epochs: 10
  optimizer_scheduler:
    eta_min: 0.0001
    T_max: 30
    type: CosineAnnealingLR
  schedule_cfg: null
  weight_decay: 0.00004
  learning_rate: 0.005
  save_as_state_dict: true
